---
sudo: required

env:
  - distribution: centos
    version: 7

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible .'

script:
  - chmod -x vault_test.txt
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup --volume="${PWD}":/root ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/wordpress.yml --vault-password-file /root/vault_test.txt --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/wordpress.yml --vault-password-file /root/vault_test.txt --skip-tags "restart,deploy,restore,repo,test,selinux"'
  - 'sudo docker rm -f "$(cat ${container_id})"'

#NOTE: "test" tag is for OpenResty role default site
