---
sudo: required

env:
  - distribution: centos
    version: 7

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible .'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup --volume="${PWD}":/root ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/wordpress.yml --vault-password-file ~/vault_test.txt --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/wordpress.yml --vault-password-file ~/vault_test.txt'
  - 'sudo docker rm -f "$(cat ${container_id})"'
  # Test CV
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup --volume="${PWD}":/root ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/cv.yml --vault-password-file ~/vault_test.txt --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/cv.yml --vault-password-file ~/vault_test.txt'
  - 'sudo docker rm -f "$(cat ${container_id})"'
