# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: all.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 08-Apr-2018

---
# Variables listed here are applicable to all host groups

##### ADMIN Email #####
admin_email: "{{ vault_admin_email }}"
admin_email_server: "{{ vault_admin_email_server }}"
admin_email_password: "{{ vault_admin_email_password }}"
admin_name: "{{ vault_admin_name }}"

##### Updates #####
# Enable or disable automatic updates
auto_updates: true

# CI testing, this should only be set to true for testing
updates_ci_test: false


##### SE Linux #####

# Security Enhanced Linux Disable or Enable
# true == disabled
# false == enabled
sel_disable: true

# CI test, this should only be set to true for CI testing
sel_ci_test: false


##### MariaDB #####
# MariaDB settings

# These are the WordPress database settings

# Create a new database for WordPress or use an existing one
# true: create new database
# false: upload existing database
mariadb_new_db: false
mariadb_db_name: "{{ vault_mariadb_db_name }}"
mariadb_db_user: "{{ vault_mariadb_db_user }}"
mariadb_db_user_password: "{{ vault_mariadb_db_user_password }}"

mariadb_db_backup_dir: ../../databases

# filename of existing database
# NOTE: if mariadb_new_db == false
mariadb_db_file_name: "{{ vault_mariadb_db_file_name }}"

# If the server / cloud service provider provides a firewall to limit access to certain IP's
# you can safetly open the MariaDB port. If not, I would advise keeping it closed.
mariadb_open_port: false
mariadb_port: 3306
mariadb_set_root_password: true
mariadb_root_password: "{{ vault_mariadb_root_password }}"

# CI test, this should only be set to true for testing
mariadb_ci_test: false

##### Redis #####

# Redis Cache setting
# See redis.config

rd_mem: 512mb
rd_mem_pol: allkeys-lru

# Optimize system for Redis
# NOTE: BROKEN
rd_optimize: false

# CI testing, this should only be set to true for testing
rd_ci_test: false


##### NGINX / OpenResty #####

# htpasswd settings
htpasswd_user: "{{ vault_htpasswd_user }}"
htpasswd_pass: "{{ vault_htpasswd_pass }}"

# This is used for the nginx server configuration, but access to the
# WordPress site is not restricted by a named host.
nginx_ipv6:  2607:5300:201:2100::5:1111 # Now only applies to proof of concept cloudflare role
nginx_port: 443
server_hostname: "{{ vault_server_hostname }}" # REQUIRED for self-signed SSL certificates in openresty role


# Web Directories
# Default directory
resty_default_web_dir: /usr/local/openresty/nginx/html/default
# Sites directory
resty_sites_dir: /usr/local/openresty/nginx/sites

# Config directory
resty_conf_dir: /usr/local/openresty/nginx/conf
# Log directory
resty_log_dir: /var/log/openresty

openresty_version: 1.11.2.5
openresty_download_url: https://openresty.org/download/openresty-
with_luajit: false
with_dav: false
with_flv: false
with_geoip: true
with_gzip_static: true
with_image_filter: true
with_realip: true
with_stub_status: false
with_ssl: true
with_sub: true
with_xslt: true
with_ipv6: true
with_mail: true
with_mail_ssl: true
with_secure_link: true
with_pcre_jit: false
with_debug: true
with_auth_request: true
with_addition: true
with_gunzip: true
with_postgres: false
with_http2: true
with_file_aio: false

##### Compile from source or install from repo #####
# set to false to install from repo
resty_install_from_source: true

##### Compile Threads #####
resty_compile_threads: 2

### TODO: Refactor options
# Display default web server settings for hosting static files
resty_default_server: false
# Static CV server
resty_cv_server: false
# Configure OpenResty for WordPress w/ Redis
resty_install_wp: true
# use self signed ssl cert
resty_SSL_self_signed: true
###

# SSL key directory
resty_SSL_key_dir: /etc/ssl/private
# SSL cert directory
resty_SSL_cert_dir: /etc/ssl/certs

# OpenResty web service user and group
resty_web_user: nginx

##### These modules are depreciated #####
with_sha1: "/usr/include/openssl"
with_md5: "/usr/include/openssl"

# CI test, should only be set to true for testing
resty_ci_test: false


##### PHP #####

php_upload_max_filesize: "15M"
php_memory_limit: "512M"

# PHP Socket
php_sock: /var/run/wordpress.sock

# Should only be set to true for testing
php_ci_test: false


##### IPv6 Network #####
# server network settings

# Configure the server's static IPv6 address
## Provider Dependent ##
# true: configures the server for IPv6 if not already preconfigured
# If you are using OVH public cloud or OVH OpenStack, this should be set to true
# If you are using DigitalOcean, this should be set to false
ipv6_setup: true

# The server IPv4 address is only necessary if with to use the proof of concept
# cloudflare role
ipv4_addr: 54.39.111.111
ipv6_addr: 2607:5300:201:2100::5:1111/128
ipv6_gate: 2607:5300:201:2100::1

# Overrides CI testing default
# This should only be set to true for testing
ipv6_ci_test: false


##### Firewalld and Fail2Ban #####

firewalld_installed: true

# CloudFlare account Email
cf_email: "{{ vault_cf_email }}"
# CloudFlare accoutn API key
cf_key: "{{ vault_cf_key }}"

# times are in seconds
f2b_bantime: 864000
f2b_findtime: 10800
f2b_maxretry: 4
f2b_whitelist_ip: "{{ vault_f2b_whitelist_ip }}"
f2b_destemail: "{{ vault_f2b_destemail }}"
f2b_sender: "{{ vault_f2b_sender }}"

# CI test, this should only be set to true for testing
f2b_ci_test: false


##### WordPress #####

wp_uploads_backup_dir: ../../uploads

# WordPress Salt
wp_cache_salt: "{{ vault_wp_cache_salt }}"
# Disable All Updates
# By default automatic updates are enabled, set this value to true to disable all automatic updates
auto_up_disable: false
#Define Core Update Level
# true  = Development, minor, and major updates are all enabled
# false = Development, minor, and major updates are all disabled
# minor = Minor updates are enabled, development, and major updates are disabled
core_update_level: true

# CI test, should only be set to true for CI testing
wp_ci_test: false


##### CloudFlare #####

cf_bypass_name: srv.example.com
cf_new_record: true
cf_zone_id: your_zone_id
cf_A_id: your_A_id
cf_AAAA_id: your_AAAA_id
cf_proxied_AAAA_id: your_proxied_AAAA_id
